apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeproxyoperator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: delete-kubeproxy
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: delete-kubeproxy-kubeproxydeleter
subjects:
  - kind: ServiceAccount
    name: kubeproxyoperator
roleRef:
  kind: Role
  name: delete-kubeproxy
  apiGroup: rbac.authorization.k8s.io
