apiVersion: apps/v1
kind: Deployment
metadata:
  name: corednsoperator
  namespace: kube-system
  labels:
    app: corednsoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corednsoperator
  template:
    metadata:
      labels:
        app: corednsoperator
    spec:
      serviceAccountName: corednsoperator
      containers:
        - name: coredensoperator
          image: ghcr.io/markjgardner/core-dns-bouncer:latest
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: corednsoperator
spec:
  selector:
    app: corednsoperator
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer