apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeproxyoperator
  namespace: kube-system
  labels:
    app: kubeproxyoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeproxyoperator
  template:
    metadata:
      labels:
        app: kubeproxyoperator
    spec:
      serviceAccountName: kubeproxyoperator
      containers:
        - name: kubeproxyoperator
          image: ghcr.io/markjgardner/kube-proxy-bouncer:latest
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kubeproxyoperator
spec:
  selector:
    app: kubeproxyoperator
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer